apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: daptin
spec:
  ingressClassName: nginx
  rules:
    - host: daptin.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: daptin
                port:
                  name: http
