apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: daptin
resources:
  - namespace.yaml
  - configmap.yaml
  - pvc.yaml
  - service.yaml
  - deployment.yaml
commonLabels:
  app.kubernetes.io/part-of: daptin
