apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: daptin
resources:
  - namespace.yaml
  - configmap.yaml
  - pvc.yaml
  - service.yaml
  - service-headless.yaml
  - deployment.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: daptin
    includeSelectors: false
