apiVersion: v1
kind: Service
metadata:
  name: daptin
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app.kubernetes.io/name: daptin
    app.kubernetes.io/instance: daptin
