apiVersion: v1
kind: Service
metadata:
  name: daptin-headless
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: olric
      port: 5336
      targetPort: olric
      protocol: TCP
    - name: olric-member
      port: 5337
      targetPort: olric-member
      protocol: TCP
  selector:
    app.kubernetes.io/name: daptin
    app.kubernetes.io/instance: daptin
