site_name: Daptin
site_favicon: images/favicon.png
pages:
- Daptin:
  - Introduction: index.md
  - Installation: setting-up/installation.md
  - Getting started: setting-up/settingup.md
  - User management: setting-up/access.md
  - Data model: setting-up/data_modeling.md
- API reference: apis/crud.md
- Actions:
  - What are actions: actions/actions.md
  - Actions list: actions/default_actions.md
  - Examples: actions/examples.md
- Features:
  - GraphQL: features/enable-graphql.md
  - Data Auditing: features/enable-data-auditing.md
  - Multilingual Table: features/enable-multilingual-table.md
  - SMTP/IMPS server: features/enable-smtp-imap.md
  - Logs: features/enable-logs.md
  - State tracking: state/machines.md
  - OAuth Connections: extend/oauth_connection.md
  - OAuth Tokens: extend/oauth_token.md
  - Integrations Overview: integrations/overview.md
  - Cloud store: cloudstore/cloudstore.md
  - Cloud store backed asset columns: cloudstore/assetcolumns.md
  - Sub-sites:
    - Creating a subsite: subsite/subsite.md
    - Live editing a subsite: subsite/grapes.md
    - Basic Authentication: subsite/basic_auth.md
- Reference Documents:
  - Data store format: data-modeling/data_storage.md
  - Data exchange and sync: extend/data_exchange.md
  - Data streams: streams/streams.md
  - Enable/Disabling features: setting-up/enabling-features.md
theme:
  name: null
  custom_dir: 'rtd_dropdown/'
extra_css:
- css/theme_extra.css
google_analytics: ['UA-114227400-1', 'docs.dapt.in']
markdown_extensions:
- toc:
    permalink: Link
- admonition
- codehilite
- pymdownx.superfences
- pymdownx.tasklist
- pymdownx.magiclink